import { createAsyncThunk, createSlice, PayloadAction } from "@reduxjs/toolkit";
import { log } from "console";
import { RootState, AppThunk } from "../../store";
import { Products } from "./interfaces/Products";
import { sliceIntoChunks, sortingList } from "./utils/utils";
export interface PaginationState {
  listData: any[];
  filterList: any[];
  page: number;
  orderDirection: boolean;
}

type Column = {
  productId: string;
};

const initialState: PaginationState = {
  listData: [],
  filterList: [],
  page: 0,
  orderDirection: true,
};

export const tableSlice = createSlice({
  name: "table",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    setTableData: (state, action: PayloadAction<any>) => {
      state.listData = action.payload;
      state.filterList = action.payload;
    },
    nextPage: (state, action: PayloadAction<number>) => {
      console.log("setPage", action.payload);
      // Redux Toolkit allows us to write "mutating" logic in reducers. It
      // doesn't actually mutate the state because it uses the Immer library,
      // which detects changes to a "draft state" and produces a brand new
      // immutable state based off those changes
      state.page += 1;
    },
    previousPage: (state, action: PayloadAction<number>) => {
      console.log("setPage", action.payload);
      state.page -= 1;
    },
    sortData: (state, action: PayloadAction<any>) => {
      const { listData, column, order } = action.payload;

      const sortData = sortingList(listData.flat(), column, order);
      const result = sliceIntoChunks(sortData, 10);
      state.filterList = result;
    },
    filterDataList: (state, action: PayloadAction<any>) => {
      const { listData, column, value } = action.payload;

      const filteredData = listData.flat().filter((item: any) => {
        return (
          item[column].substring(0, value.length).toLowerCase() ===
          value.toLowerCase()
        );
      });
      const result = sliceIntoChunks(filteredData, 10);
      if (result.length > 0) {
        state.filterList = result;
      } else {
        state.filterList = listData;
      }
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  //   extraReducers: (builder) => {
  //     console.log(builder);
  //     builder
  //       .addCase(incrementAsync.pending, (state) => {
  //         state.status = "loading";
  //       })
  //       .addCase(incrementAsync.fulfilled, (state, action) => {
  //         state.status = "idle";
  //         state.value += action.payload;
  //       })
  //       .addCase(incrementAsync.rejected, (state) => {
  //         state.status = "failed";
  //       });
});

export const selectPagination = (state: RootState) => state.table;

export const {
  nextPage,
  previousPage,
  setTableData,
  sortData,
  filterDataList,
} = tableSlice.actions;

export default tableSlice.reducer;
